In [26]:
# Convert the tables to a standard format
import pandas as pd
import glob
import numpy as np
# import qgrid

In [27]:
common_labels = ['cellID','cluster_id','cluster_label','subclass_label','class_label','embedding1','embedding2']
rna_cols = ['cell','cluster_id','cluster_label','subclass_label','class_label','',''] 
atac_cols = ['cell','Li et al 2020 SubType','Li et al 2020 MajorType','Li et al 2020 Class','tsne1','tsne2']

In [28]:
flist = glob.glob('*RNA*.gz')
analyses = pd.DataFrame(columns=['AnalysisID','Contact','file','Description'])
for i,f in enumerate(flist):
    data=pd.read_csv(f,sep='\t')
    data = data.rename(columns={j:k for (j,k) in zip(rna_cols,common_labels)})
    
    # Add missing columns
    for c in common_labels:
        if c not in data.columns:
            data[c] = np.NaN
            
    ucols = common_labels + list( set(data.columns) - set(common_labels) )
    data = data[ucols]
    sample = f.split('/')[-1].strip('.tsv.gz')
    data.to_csv('Analysis%d.csv.gz' % i)
    analyses=analyses.append(pd.Series({'AnalysisID':  'Analysis%d'% i, 'Contact': 'emukamel@ucsd.edu',
                                       'file': 'Analysis%d.csv.gz' % i,
                                       'Description': f}),ignore_index=True)
analyses.to_csv('Analyses.csv.gz',index=False)
analyses

/cndd/local/bin/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (64) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,AnalysisID,Contact,file,Description
0,Analysis0,emukamel@ucsd.edu,Analysis0.csv.gz,Table_S4e_snRNA_10X_v3_B_metadata.tsv.gz
1,Analysis1,emukamel@ucsd.edu,Analysis1.csv.gz,Table_S4b_scRNA_10X_v3_A_metadata.tsv.gz
2,Analysis2,emukamel@ucsd.edu,Analysis2.csv.gz,Table_S4a_scRNA_SMART_metadata.tsv.gz
3,Analysis3,emukamel@ucsd.edu,Analysis3.csv.gz,Table_S4c_scRNA_10X_v2_A_metadata.tsv.gz
4,Analysis4,emukamel@ucsd.edu,Analysis4.csv.gz,Table_S4d_snRNA_SMART_metadata.tsv.gz
5,Analysis5,emukamel@ucsd.edu,Analysis5.csv.gz,Table_S4f_snRNA_10X_v3_A_metadata.tsv.gz

In [29]:
f = 'Table_S4g_open_chromatin_metadata.tsv.gz'
analyses = pd.read_csv('Analyses.csv.gz')
i=analyses.shape[0]+1
analyses=analyses.append(pd.Series({'AnalysisID':  'Analysis%d'% i, 'Contact': 'emukamel@ucsd.edu',
                                   'file': 'Analysis%d.csv.gz' % i,
                                   'Description': 'MOp snATAC-Seq with UMAP'}),ignore_index=True)
analyses.to_csv('Analyses.csv.gz', index=False)

data=pd.read_csv(f,sep='\t')
mc_cols = ['cell','SubCluster','MajorCluster','','umap_0','umap_1']
data = data.rename(columns={j:k for (j,k) in zip(mc_cols,common_labels)})
    
# Add missing columns
for c in common_labels:
    if c not in data.columns:
        data[c] = np.NaN
            
ucols = common_labels + list( set(data.columns) - set(common_labels) )
data = data[ucols]
sample = f.split('/')[-1].strip('.tsv.gz')
data.to_csv('Analysis%d.csv.gz' % i)

analyses

,AnalysisID,Contact,file,Description
0,Analysis0,emukamel@ucsd.edu,Analysis0.csv.gz,Table_S4e_snRNA_10X_v3_B_metadata.tsv.gz
1,Analysis1,emukamel@ucsd.edu,Analysis1.csv.gz,Table_S4b_scRNA_10X_v3_A_metadata.tsv.gz
2,Analysis2,emukamel@ucsd.edu,Analysis2.csv.gz,Table_S4a_scRNA_SMART_metadata.tsv.gz
3,Analysis3,emukamel@ucsd.edu,Analysis3.csv.gz,Table_S4c_scRNA_10X_v2_A_metadata.tsv.gz
4,Analysis4,emukamel@ucsd.edu,Analysis4.csv.gz,Table_S4d_snRNA_SMART_metadata.tsv.gz
5,Analysis5,emukamel@ucsd.edu,Analysis5.csv.gz,Table_S4f_snRNA_10X_v3_A_metadata.tsv.gz
6,Analysis7,emukamel@ucsd.edu,Analysis7.csv.gz,MOp snATAC-Seq with UMAP

In [30]:
f = 'Table_S4g_open_chromatin_metadata.tsv.gz'
analyses = pd.read_csv('Analyses.csv.gz')
i=analyses.shape[0]+1
analyses=analyses.append(pd.Series({'AnalysisID':  'Analysis%d'% i, 'Contact': 'emukamel@ucsd.edu',
                                   'file': 'Analysis%d.csv.gz' % i,
                                   'Description': 'MOp snATAC-Seq with tSNE'}),ignore_index=True)
analyses.to_csv('Analyses.csv.gz', index=False)

data=pd.read_csv(f,sep='\t')
mc_cols = ['cell','SubCluster','MajorCluster','','tsne_0','tsne_1']
data = data.rename(columns={j:k for (j,k) in zip(mc_cols,common_labels)})
    
# Add missing columns
for c in common_labels:
    if c not in data.columns:
        data[c] = np.NaN
            
ucols = common_labels + list( set(data.columns) - set(common_labels) )
data = data[ucols]
sample = f.split('/')[-1].strip('.tsv.gz')
data.to_csv('Analysis%d.csv.gz' % i)

analyses

,AnalysisID,Contact,file,Description
0,Analysis0,emukamel@ucsd.edu,Analysis0.csv.gz,Table_S4e_snRNA_10X_v3_B_metadata.tsv.gz
1,Analysis1,emukamel@ucsd.edu,Analysis1.csv.gz,Table_S4b_scRNA_10X_v3_A_metadata.tsv.gz
2,Analysis2,emukamel@ucsd.edu,Analysis2.csv.gz,Table_S4a_scRNA_SMART_metadata.tsv.gz
3,Analysis3,emukamel@ucsd.edu,Analysis3.csv.gz,Table_S4c_scRNA_10X_v2_A_metadata.tsv.gz
4,Analysis4,emukamel@ucsd.edu,Analysis4.csv.gz,Table_S4d_snRNA_SMART_metadata.tsv.gz
5,Analysis5,emukamel@ucsd.edu,Analysis5.csv.gz,Table_S4f_snRNA_10X_v3_A_metadata.tsv.gz
6,Analysis7,emukamel@ucsd.edu,Analysis7.csv.gz,MOp snATAC-Seq with UMAP
7,Analysis8,emukamel@ucsd.edu,Analysis8.csv.gz,MOp snATAC-Seq with tSNE